### ISSUE TITLE
RuntimeError: ANDROID_SDK or ANDROID_HOME needs to be set

### ISSUE THREAD

**Issue by dnKaratzas** [facebook/screenshot-tests-for-android#134] opened 2017-11-17 09:12 UTC
Hello. My environment is:
Mac - High Sierra.
Gradle Version : 2.3.1

I have set environment variable in my ~/.bash_profile:
```
export ANDROID_SDK=/Users/username/Library/Android/sdk
export PATH=$PATH:$ANDROID_SDK
export PATH=$PATH:$ANDROID_SDK/tools
export PATH=$PATH:$ANDROID_SDK/platform-tools
export PATH=$PATH:$ANDROID_SDK/build-tools/27.0.0
```

When i run on terminal echo $ANDROID_SDK the output is:
/Users/username/Library/Android/sdk/

Also if i run python from terminal is working also:
```
>>> import os
>>> android_sdk = os.environ.get('ANDROID_SDK')
>>> android_sdk
'/Users/dionisioskaratzas/Library/Android/sdk/'
>>> 
```

But when i try to record the screenshot tests with 'gradle recordMode screenshotTests' i get this error:

```
:app:pullScreenshots
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/username/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.4.4/869ab9b4e4da5ea96ddf7923f650d7029c8c798/plugin-0.4.4.jar/android_screenshot_tests/pull_screenshots.py", line 333, in <module>
  File "/Users/username/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.4.4/869ab9b4e4da5ea96ddf7923f650d7029c8c798/plugin-0.4.4.jar/android_screenshot_tests/pull_screenshots.py", line 289, in main
  File "/Users/username/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.4.4/869ab9b4e4da5ea96ddf7923f650d7029c8c798/plugin-0.4.4.jar/android_screenshot_tests/pull_screenshots.py", line 285, in setup_paths
  File "/Users/username/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.4.4/869ab9b4e4da5ea96ddf7923f650d7029c8c798/plugin-0.4.4.jar/android_screenshot_tests/common.py", line 27, in get_android_sdk
RuntimeError: ANDROID_SDK or ANDROID_HOME needs to be set

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:pullScreenshots'.
> Process 'command 'python'' finished with non-zero exit value 1
```

What might be wrong...

**Comment by xiphirx** [comment] 2017-11-20 18:21
Try killing Gradle and its daemon, it might be running with an outdated environment.

**Comment by dnKaratzas** [comment] 2017-11-29 12:40
Tried but same result. Updated also to version 0.5.0 same again. Also downloaded your example project and have the same issue.

**Comment by xiphirx** [comment] 2017-11-30 19:46
What is the output of `which python` ?

**Comment by xiphirx** [comment] 2017-12-14 06:38
Closing due to lack of information and high probability of an external issue.

**Closed by xiphirx** 2017-12-14 06:38 UTC

**Comment by ddeleon92** [comment] 2020-04-07 18:16
@xiphirx any chance of reopening this? I am having this issue currently I have tried everything to fix and nothing is working. to pick up where you 2 left off "which python" returns /Library/Frameworks/Python.framework/Versions/2.7/bin/python

**Comment by xiphirx** [comment] 2020-04-07 19:44
This is a problem with your environment, not the project. Somehow your environment variables are not being propagated properly. How are you invoking gradle? Is it through IntelliJ/Android Studio? If so you need to ensure that you specify `sdk.dir` in your `local.properties` file. Otherwise simply exporting one of the variables will work just fine.

**Comment by ddeleon92** [comment] 2020-04-07 20:07
@xiphirx yes I am using Android Studio and sdk.dir is set properly. It was working fine then I woke up yesterday morning to this error. No changes were made to provoke it, it just started failing on me.

**Comment by ddeleon92** [comment] 2020-04-07 20:15
also if the problem is with pyhon python 2.7 is offically Deprecatedas of January 1st so there's no fixing it on their end either... 
`DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support`

**Comment by xiphirx** [comment] 2020-04-07 20:27
No, nothing is wrong with python. The issue is that your environment variables are screwed up and are not being propagated to the gradle process and eventually the spawned python process. This is something on your end, it could be a whole myriad of different things. 

You can try invoking gradle directly in a terminal after you ensure you export `ANDROID_HOME` to the correct location.

**Comment by clintonbuie** [comment] 2020-08-05 03:00
I ran into the same problem as well.  I figured out a work around though:

Go to `Android Studio` -> `Preferences...` -> `Terminal` and add either `ANDROID_HOME` or `ANDROID_SDK` path to System Environment Variables

![Screen Shot 2020-08-04 at 7 57 58 PM](https://user-images.githubusercontent.com/314498/89367137-281ddd00-d68d-11ea-9f25-2a99f01f773d.png)

Hope this helps . . .

**Comment by MohamedMedhat1998** [comment] 2020-08-07 12:04
I have the same problem with `Ubuntu 18.04.4 LTS`.  
I have set the environment variables correctly. And I have tried 
```
>>> import os
>>> android_sdk = os.environ.get('ANDROID_SDK')
>>> print(android_sdk)
```
and got the expected value.  


> This is a problem with your environment, not the project. Somehow your environment variables are not being propagated properly. How are you invoking gradle? Is it through IntelliJ/Android Studio? If so you need to ensure that you specify `sdk.dir` in your `local.properties` file. Otherwise simply exporting one of the variables will work just fine.

I also have these settings set up correctly.
I have tried @clintonbuie solution but didn't help.  
Any updates on this?

**Comment by sanginovs** [comment] 2020-08-20 17:42
I ran into the same issue. Here's what i did to solve it:

1. In the terminal run:
`$ nano ~/.bash_profile`

2. Add 
`export ANDROID_HOME=~/Path/to/your/Android/sdk
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/emulator`
Close and save it.

3. Run this cmd in terminal:
`source ~/.bash_profile`
