### ISSUE TITLE
Fail with android gradle plugin 3.0.0

### ISSUE THREAD

**Issue by vincentnock** [facebook/screenshot-tests-for-android#108] opened 2017-09-07 16:09 UTC
I know that this gradle plugin is still in beta, but if someone could find a way to make it work with it, that would be awesome.

Problem appears when using the version 3.0.0 in the example app
```groovy
dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0-beta4'
        classpath 'com.facebook.testing.screenshot:plugin:0.4.4-beta'
    }
```

Complete stacktrace :
```
app-example-androidjunitrunner vincent$ ./gradlew screenshotTests --stacktrace
Parallel execution is an incubating feature.

> Configure project :app
Configuration 'androidTestCompile' in project ':app' is deprecated. Use 'androidTestImplementation' instead.
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
Configuration 'testCompile' in project ':app' is deprecated. Use 'testImplementation' instead.

> Task :app:connectedDebugAndroidTest
Starting 2 tests on LG-H850 - 7.0


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:pullScreenshots'.
> Expected task 'packageDebugAndroidTest' output files to contain exactly one file, however, it contains no files.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:pullScreenshots'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.IllegalStateException: Expected task 'packageDebugAndroidTest' output files to contain exactly one file, however, it contains no files.
        at org.gradle.api.internal.file.AbstractFileCollection.getSingleFile(AbstractFileCollection.java:59)
        at org.gradle.api.file.FileCollection$getSingleFile$0.call(Unknown Source)
        at com.facebook.testing.screenshot.build.ScreenshotsPlugin.getTestApkOutput(ScreenshotsPlugin.groovy:151)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:479)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:191)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:80)
        at org.gradle.internal.metaobject.BeanDynamicObject$GroovyObjectAdapter.invokeOpaqueMethod(BeanDynamicObject.java:579)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:506)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:191)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:80)
        at com.facebook.testing.screenshot.build.ScreenshotsPlugin$_apply_closure1$_closure9$_closure10.doCall(ScreenshotsPlugin.groovy:48)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
        at org.gradle.api.internal.file.DefaultFileOperations.exec(DefaultFileOperations.java:181)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1071)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1066)
        at org.gradle.api.Project$exec$3.call(Unknown Source)
        at com.facebook.testing.screenshot.build.ScreenshotsPlugin$_apply_closure1$_closure9.doCall(ScreenshotsPlugin.groovy:47)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:681)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:656)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 27 more
```

**Comment by vincentnock** [comment] 2017-09-11 14:07
I found what was going on.
With this new gradle plugin, apk are stored in a subdirectory 

So this part does not work anymore, in `ScreenshotsPlugin.groovy`:

```groovy ScreenshotsPlugin.groovy
String getTestApkOutput(Project project) {

  return project.tasks.getByPath(project.screenshots.testApkTarget).getOutputs().getFiles().filter {
    it.getAbsolutePath().endsWith ".apk"
  }.getSingleFile().getAbsolutePath()
}
```

I replaced it with something like that:

```groovy
String getTestApkOutput(Project project) {
  return project.android.testVariants.first().outputs.first().outputFile
}
```

I don't know if it's consistant enough to be correct for any project configuration, but it works in my case, and for test project too.

**Comment by JorgeCastilloPrz** [comment] 2017-09-13 11:23
May be you could open a PR with that ?

**Comment by emanzanoaxa** [comment] 2017-10-31 13:13
Now the Gradle Android plugin 3 is stable I think this is important, maybe we can release a version with a quick fix?

**Comment by xiphirx** [comment] 2017-11-01 00:35
Possibly, I would much rather fix the test target weirdness all in one go by having per-variant screenshot test tasks that wouldn't require any hacky code to determine the output apk.

**Comment by rrupsing** [comment] 2017-11-03 18:35
After updating to Android Studio 3.0 and google() I can build and run within Android Studio but ./gradlew doesn't work for me anymore...how did you guys get around that issue?

`> Could not resolve all files for configuration ':classpath'.
   > Could not find com.android.tools.build:gradle:3.0.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.pom
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.jar
     Required by:
         project :
`

**Comment by xiphirx** [comment] 2017-11-07 17:57
@rrupsing that isnt related to this issue and doesn't seem related to this library at all.

**Comment by vanniktech** [comment] 2017-11-07 18:43
Anything that we can do to speed this up?

**Comment by xiphirx** [comment] 2017-11-07 18:50
I have local changes that upgrade everything to AGP 3, however I was running into a dex merge error saying there were duplicate definitions for com.facebook.testing.screenshot.R. I was in the middle of debugging that issue last week. I will be taking a look again today/this week. Sorry this is taking so long, I'm a bit swamped right now with other things :(

If anyone wishes to upgrade AGP and submit a PR to expedite the process, I'd happy to review it.

**Comment by vanniktech** [comment] 2017-11-07 18:58
I don't think it would make sense to duplicate this effort of updating to AGP 3.0. I'm happy to review and test and early versions of this.

**Comment by xiphirx** [comment] 2017-11-07 22:24
Things should now be working as of ec53df421b20b3d20a402137a35bb5f60cd346e8 @vanniktech do you mind trying out the change?

**Comment by vanniktech** [comment] 2017-11-07 22:31
I'll do so tomorrow or latest Thursday, European time.

**Comment by vanniktech** [comment] 2017-11-13 09:40
Sorry it took a bit longer. I checked out https://github.com/josedlpozo/screenshot-tests-for-android and ran it locally and I got the following exception:

```
Starting 12 tests on Nexus 6P - 8.0.0

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ui-demo:pullScreenshots'.
> Expected task 'packageDebugAndroidTest' output files to contain exactly one file, however, it contains no files.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':ui-demo:pullScreenshots'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.IllegalStateException: Expected task 'packageDebugAndroidTest' output files to contain exactly one file, however, it contains no files.
        at org.gradle.api.internal.file.AbstractFileCollection.getSingleFile(AbstractFileCollection.java:59)
        at org.gradle.api.file.FileCollection$getSingleFile$0.call(Unknown Source)
        at com.facebook.testing.screenshot.build.ScreenshotsPlugin.getTestApkOutput(ScreenshotsPlugin.groovy:151)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:479)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:191)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:80)
        at org.gradle.internal.metaobject.BeanDynamicObject$GroovyObjectAdapter.invokeOpaqueMethod(BeanDynamicObject.java:579)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:506)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:191)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:80)
        at com.facebook.testing.screenshot.build.ScreenshotsPlugin$_apply_closure1$_closure9$_closure10.doCall(ScreenshotsPlugin.groovy:48)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
        at org.gradle.api.internal.file.DefaultFileOperations.exec(DefaultFileOperations.java:187)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1076)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1071)
        at org.gradle.api.Project$exec$4.call(Unknown Source)
        at com.facebook.testing.screenshot.build.ScreenshotsPlugin$_apply_closure1$_closure9.doCall(ScreenshotsPlugin.groovy:47)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:722)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:695)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 29 more
```

**Comment by mhiew** [comment] 2017-11-13 16:47
@vanniktech 

I think you may be testing the wrong branch. The changes are within the master branch of this repo.

https://github.com/facebook/screenshot-tests-for-android/commit/ec53df421b20b3d20a402137a35bb5f60cd346e8

**Comment by rrupsing** [comment] 2017-11-14 17:49
Also getting this issue. Are you planning to do a new release with the fix for Android Studio 3.0?

**Comment by xiphirx** [comment] 2017-11-15 19:23
Yes @vanniktech it seems like you tested a fork of this library. I have tested this locally with the sample apps and they work. I'll look into providing a new release with the fix. Closing.

**Closed by xiphirx** 2017-11-15 19:23 UTC
Labels: bug

**Comment by vanniktech** [comment] 2017-11-17 13:36
Thanks for all of your work @xiphirx

**Comment by ubuntudroid** [comment] 2017-12-19 15:08
@xiphirx I still get this with 0.5.0:
`DexArchiveMergerException: Unable to merge dex`
caused by
`Multiple dex files define Lcom/facebook/testing/screenshot/R`

You mentioned the same issue in one of your comments above - how did you get rid of it?

**Comment by ubuntudroid** [comment] 2017-12-19 16:37
Found the issue: it was caused by using
`compile 'com.facebook.testing.screenshot:layout-hierarchy-common:0.5.0'`

Going without it for now, but would be good to know how to fix this for the future.

**Comment by ubuntudroid** [comment] 2017-12-20 11:00
Created a test project for you to test the above mentioned issue: https://github.com/ubuntudroid/FacebookScreenshotTest

Just add `compile 'com.facebook.testing.screenshot:layout-hierarchy-common:0.5.0'` to the app's dependencies and observe the described issue. Hope that helps.
