### ISSUE TITLE
[Build Error] Duplicate class

### ISSUE THREAD

**Issue by rcd27** [facebook/screenshot-tests-for-android#221] opened 2019-05-27 14:22 UTC
There are similar classes in different modules and gradle can't complete the build with multiple specific errors like:
`Duplicate class android.support.coreui.R$bool found in modules jetified-core-0.9.0.jar (com.facebook.testing.screenshot:core:0.9.0) and jetified-layout-hierarchy-common-0.9.0.jar (com.facebook.testing.screenshot:layout-hierarchy-common:0.9.0)`

**Comment by xiphirx** [comment] 2019-05-29 01:18
Dupe of #217

**Closed by xiphirx** 2019-05-29 01:18 UTC
